### ISSUE TITLE
[FEAT] Manifest v3

### ISSUE THREAD

**Issue by GeoNomad** [willbchang/chrome-read-later#213]
I have noticed that installing from the files brings up a warning that the manifest file is version 2 and that this will be deprecated next year.

A quick look at the documentation makes it look like this is more than a need to just replace the file as background pages will be replaced by service workers.

Being new to extensions, I am not sure how big an issue that is.

But I don't want to spend too much time modifying the code to find that a major change will be required later. I have been working on a cloud sync to use Read Later from Chrome on my phone, which is working great.

Will/Can you update to v3?

**Comment by willbchang** [comment]
Hi Peter, thanks for reminding it. I think the upgrade won't affect it's functionalities, hence I will finish this in my spare time before being deprecated. It won't be long. 😄

Pull requests are always welcome!

**Comment by GeoNomad** [comment]
Thank you for the response, Will.

Yes, I will open source the code when I am a little further along. At this point, the sync only works one way - I just added         jQuery.post('https://....com/....php', `id=${page.date}&url=${page.url}`); in set(page) in chrome/storage.mjs.
And jQuery.post('https://....com/....php', `remove=${url}`); to remove(url).

The rest is php to display the list and keep my private history list. I am looking at how to feed items that have been read back to the extension. A better way would be to add a new sync to updateStorage and use removeDeletePages, I guess.

For now it is just for my own use, anyway.

**Comment by willbchang** [comment]
Hi @GeoNomad 

It's been a busy year at work and life. Finally I got time to upgrade this extension to manifest 3. The code has been merged to master at #215, all the main changes that needs to be aware are listed in the pr. Feel free to update your code base on the master branch. I'm happy to answer any question. :)
