### ISSUE TITLE
Export data

### ISSUE THREAD

**Issue by willbchang** [willbchang/chrome-read-later#49]
https://stackoverflow.com/questions/23160600/chrome-extension-local-storage-how-to-export

**Comment by willbchang** [comment]
chrome-extension://fbmfcfkokefgbmfcjahdmomlifclekib/popup/popup.html should work if it installed from  chrome web store

**Comment by mcejp** [comment]
I have been playing around a bit, and I'm liking the idea of exporting the pages as JSONL -- a list with 1 JSON object per line:

<img width="934" height="329" alt="Image" src="https://github.com/user-attachments/assets/b6a70b45-4f8c-4fec-9ca5-a15d21677205" />

Compared to real JSON (array of objects), it's still very straightforward to generate and parse, but it's also friendlier for use with any kind of text editing tools as well as version control.

As for exporting the page/video position, I think it would be nice to include it only if it is != 0. But I'm not there yet.

What do you think so far?

**Comment by mcejp** [comment]
Hi again,

my merge request is ready. Sorry for taking so long; I prototyped the implementation using Claude Code, but then it took a lot of time to clean up into something I would not be ashamed to submit 😅 

I have kept it pretty simple, for example, it is not possible to export the history. This could of course be added.

**Comment by weierz** [comment]
It's still pending review. Come on Google!

**Comment by weierz** [comment]
@mcejp It's published! The version number is 9.1.0, please check it out. Thank you for your contribution! Hope you have a great day!

**Comment by mcejp** [comment]
Fantastic, thank you! 😃
