### ISSUE TITLE
希望增加一个可选的分组功能

### ISSUE THREAD

**Issue by JosephDhF** [willbchang/chrome-read-later#94]
非常棒啊，就是我想要的功能，简洁干脆，功能到位，又不累赘，如果稍微能增加一个分组功能就好了，只要增加这一个，不需要其他了

**Comment by willbchang** [comment]
感谢你的欣赏😄。
目前阅读列表是通过添加的日期倒序排序的，分组我也有考虑过：

1. 通过网页是否有视频/音频来自动分组。
2. 通过网页的网址来自动分组。
3. 如果自定义分组/标签，在阅读列表内手动拖拽的话感觉上就不是一步到位的使用体验了。
4. 用搜索是否能够满足需求？

目前还没有想到其它的方式？想向你请教一下对**分组**的想法😉。

**Comment by JosephDhF** [comment]
一步到位的使用体验，这句话无比赞；


如果做的比较轻，是不是可以直接打断点来分组，由于浏览时候的相关性，同一个时间段浏览的内容大概率是类似的，比如我做IT的，看Python，我可能连续两个小时都在看相关网页，选择了一些精品直接收藏以便再次精读；中间半个小时可能看了点其他的，也收藏了一两个，在操作完了之后，直接在中间打个断点，就分组开了，不知道是否好实现；您说的几种也值得考虑；不过总体说，现在也蛮不错了；整体保持这种轻快的感觉非常棒；


如果需要付费支持的话，可以加我微信15855118057；

**Comment by willbchang** [comment]
我能够理解你想对其分组/断点的想法，这两天我也思考了一番，如果要实现，具体的细节如下：

## 从界面设计的角度讲：
  1. 断点的颜色、大小
  2. 断点与周围元素的间距，以及没有断点时多余的空白影响界面的美观度
  3. 断点生成和删除过程的时长和效果
## 从使用体验的角度讲：
  1. 在图标前的空白区域点击一下，出现一个断点
  2. 点击断点本身会将其删除
  3. 需要考虑断点的大小和误触的概率，因为它临近删除按钮
  3. 需要支持快捷键
## 从编程角度讲：
  1. HTML：List 里需要新增一个元素
  2. CSS： 编写元素的具体样式
  3. CSS：调节周围元素的具体样式
  2. JS：存储数据的结构需要新增一个用于储存断点的 key，类型为 boolean
  3. JS：处理点击事件的字典需要对新增的断点情况进行过滤
  4. JS：编写点击事件的具体行为：点击这个元素时，绘制/删除元素里的断点，修改存储的数据
  5. JS：初始化列表时需要选择是否渲染这个新增元素里的断点
  6. JS：需要设置新的快捷键
  7. JS：处理按键事件的字典需要对新增的断点情况进行过滤

如果我说的有什么不到位的地方，请修正。😄

**Comment by willbchang** [comment]
另外：
1. 目前可以考虑新建一个用户，比如把学习和娱乐分开。（但是这样增加了使用成本，只是一个临时的办法）
2. 这个阅读列表本身就是临时的，按照我对这类工具的使用分类
  - **书签**：永久保存，一般为不同类网站主站的分类集合，会反复浏览使用。比如 https://github.com
  - **稍后阅读**：临时保存，一般只会在看到的时候 mark 一下，稍后精读时就删除了。比如某篇博客文章
  - **阅读收藏**：永久保存，对于不可多得的好文章，会离线保存，整体分类，反复阅读。

Chrome Read Later 目前是第二类，所以我个人不太推荐在整理稍后阅读的分组上多花时间，不过这个功能使用也比较简单，我会再仔细斟酌一番。

**Comment by JosephDhF** [comment]
&nbsp; &nbsp; &nbsp; 感谢回复。


&nbsp; &nbsp; &nbsp; 我的使用场景是这样的，比如说网页上有个很好的系列教程，一天看不完我会把它收藏在稍后阅读里面，每天都可以从小程序里面调取出来学习一会儿。
&nbsp; &nbsp; &nbsp; 由于是个教程系列，也不适合作为单个文章保存，目前的文章收藏类应用，大部分保持的不是链接，而是整篇文章，但是阅读的时候就要去登陆到客户端才能看到，比如instapaper之类的，不方便；
&nbsp; &nbsp; &nbsp; 收藏在书签里，由于我的书签还是非常多的，找起来也比较累，目前这种方式，基本上满足了我的需求，断点的需求应该很小众，也许只有重度用户才会用到，比如我会开20个网页，可能需要稍微分下组，大部分场景可能用不到，onetab是通过日期来区隔的，也没有这样的手动分组功能。
&nbsp; &nbsp; &nbsp; 如果能增加一个选项，比如钉住，打开这个链接的时候，不会自动销毁，这样就更完美了，也许我的需求比较小众吧，但是还是给您反馈一下。

&nbsp;

**Comment by willbchang** [comment]
>如果能增加一个选项，比如钉住，打开这个链接的时候，不会自动销毁，这样就更完美了，也许我的需求比较小众吧，但是还是给您反馈一下。

感谢你的反馈，目前来说有这样一种途径：直接鼠标右键点击，第一个选项，这样打开的就不会销毁了。

<img width="550" alt="Screen Shot 2020-07-12 at 18 15 58" src="https://user-images.githubusercontent.com/14329786/87243839-d4441d80-c46b-11ea-89a7-9d07ea0c37cd.png">

另外我设置的有快捷键 `yy` 能直接复制链接，相应的就是右键 `Copy Link Address`.

书签的管理和查找又是另外的效率工具和方法，在此就不离题了。
